config/routes.rb
addresses = ['333 Fifth St. Winter Springs, FL 32708',
           '11 Maple Drive Jupiter, FL 33458',
           '130 Gulf St. West Palm Beach, FL 33414',
           '9948 Bay Meadows St. Opa Locka, FL 33056',
           '8201 NW. Augusta Street Winter Haven, FL 33880',
           '945 East Gonzales Street Hialeah, FL 33012',
           '803 Mayflower Street Daytona Beach, FL 32119',
           '495 Summit Ave. Orlando, FL 32810',
           '445 W. Westminster St. Winter Park, FL 32792',
           '7929 Wilson Avenue Miami, FL 33177']

Rails.application.routes.draw do
  root to: 'dashboard#index'
  resources :orders
  resources :vendors
  get :out_of_normal_deliveries, to: 'dashboard#out_of_normal_deliveries'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: %i[out_for_delivery delivered]

  belongs_to :vendor

  geocoded_by :shipping_address
  after_validation :geocode

  def days_for_delivery
    (created_at.to_i - delivered_at.to_i) / 1.day
  end

  def deliver!
    delivered!
  end
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  has_many :orders

  def delivery_days_average
    orders_count = orders.delivered.count
    return 0 if orders_count.zero?
    orders.delivered.map(&:days_for_delivery).reduce(:+) / orders_count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @q = Order.ransack(params[:q])
    @order = Order.new
    @orders = @q.result.includes(:vendor).paginate(page: params[:page]).out_for_delivery
    @vendors = Vendor.all
  end

  def out_of_normal_deliveries
    @q = Order.ransack(params[:q])
    @orders = @q.result.includes(:vendor).paginate(page: params[:page]).delivered.order(created_at: :desc)
    @vendors = {}
    Vendor.all.each do |vendor|
      @vendors[vendor.id] = {
        name: vendor.name,
        delivery_time_average: vendor.delivery_days_average
      }
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @q = Order.ransack(params[:q])
    @orders = @q.result.includes(:vendor)

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @orders, status: :ok }
    end
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.status = 'out_for_delivery'

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(
      :shipping_address,
      :tracking_number,
      :vendor_id,
      :status,
      :delivered_at,
      :order_number,
      :vendor_id
    )
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    @q = Vendor.ransack(params[:q])
    @vendors = @q.result(distinct: true)
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @vendors, status: :ok }
    end
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_vendor
    @vendor = Vendor.find(params[:id])
  end

  def vendor_params
    params.require(:vendor).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def alert_type(type)
    case type
    when 'notice'
      'success'
    when 'error'
      'danger'
    else
      type
    end
  end

  def current_page?(controller, action)
    params[:controller] == controller.to_s && params[:action] == action.to_s
  end

  def current_controller?(controller)
    params[:controller] == controller.to_s
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def vendor_name(order)
    order.vendor.try(:name)
  end

  def order_status_badge(order)
    if order.delivered?
      link_to(order.status || 'normal', 'javascript:void(0)', class: 'btn btn-success btn-xs')
    else
      'On delivery'
    end
  end

  def order_delivery_status_badge(order)
    vendor_average_delivery_time = @vendors[order.vendor_id][:delivery_time_average].abs
    order_delivery_days_duration = order.days_for_delivery.abs

    if order_delivery_days_duration <= vendor_average_delivery_time + 2
      # Normal delivery time
      link_to('Normal', 'javascript:void(0)', class: 'btn btn-success btn-xs')
    elsif order_delivery_days_duration > vendor_average_delivery_time + 4
      link_to('Very late', 'javascript:void(0)', class: 'btn btn-danger btn-xs')
    else
      link_to('Not normal', 'javascript:void(0)', class: 'btn btn-warning btn-xs')
    end
  end

  def orders_map_markers(orders)
    orders.map { |o| { lat: o.latitude, lng: o.longitude, order_number: "Order #{o.order_number}" } }
  end
end

app/helpers/vendors_helper.rb
module VendorsHelper
  def vendor_for_select_options(vendors)
    options_from_collection_for_select(vendors, 'id', 'name', @vendor.try(:id))
  end
end

app/views/dashboard/_order.html.erb
<tr>
  <td><%= order.order_number %></td>
  <td><%= vendor_name(order) %></td>
  <td><%= order.shipping_address %>
    <br>
    <%=order.latitude%>, <%=order.longitude%>
  </td>
  <td><%= order.tracking_number %></td>
</tr>

app/views/dashboard/_out_of_normal_order.html.erb
<tr>
  <td><%= order.order_number %></td>
  <td title='Average days for delivery: <%= @vendors[order.vendor_id][:delivery_time_average].abs %>'>
    <%= vendor_name(order) %>
  </td>
  <td><%= order.tracking_number %></td>
  <td><%= order.created_at %></td>
  <td><%= order.delivered_at %></td>
  <td><%= order.days_for_delivery.abs %></td>
  <td><%= order_delivery_status_badge(order) %></td>
</tr>

app/views/dashboard/_sidebar.html.erb
<div class="col-lg-3">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Create Order</h3>
    </div>
    <div class="panel-body">
      <%= form_for @order do |f| %>
        <div class="form-group">
          <%= f.label :order_number %>
          <%= f.text_field :order_number, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :vendor_id %>
          <%= f.select :vendor_id, vendor_for_select_options(@vendors), class: 'form-control' %>
          <%= link_to 'Create Vendor', new_vendor_path, class: 'btn btn-info btn-xs' %>
        </div>
        <div class="form-group">
          <%= f.label :tracking_number %>
          <%= f.text_field :tracking_number, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :shipping_address %>
          <%= f.text_field :shipping_address, class: 'form-control' %>
        </div>
        <%= f.submit 'Create', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/index.html.erb
<script>
    markers = <%=raw orders_map_markers(@orders).to_json %>;
    //add_markers(markers);
</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyARshHRf_7I_FdTAhDodxLQjYGkiYYciyA&callback=initMap" type="text/javascript">
</script>

<div class="row">
  <div class="col-lg-9">
    <h3>Orders to deliver</h3>

    <%= search_form_for(@q, url: root_path, class: 'form-inline') do |f| %>
      <div class="form-group">
        <%= f.label :order_number_cont %>
        <%= f.search_field :order_number_cont, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :tracking_number_cont %>
        <%= f.search_field :tracking_number_cont, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :vendor_name_cont %>
        <%= f.search_field :vendor_name_cont, class: 'form-control' %>
      </div>

      <%= f.submit class: 'btn btn-default' %>
    <% end %>
    <br>
    <div class="form-group">
      <div style='width: 800px;'>
        <div id="map" style='width: 800px; height: 400px;'></div>
      </div>
    </div>

    <br>
      <%= will_paginate @orders %>
    <br>


    <table class="table table-stripped">
      <thead>
        <tr>
          <th>Order Number</th>
          <th>Vendor</th>
          <th>Shipping Address</th>
          <th>Tracking Number</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'dashboard/order', collection: @orders, as: :order %>
      </tbody>
    </table>
  </div>
  <%= render partial: 'sidebar' %>
</div>

app/views/dashboard/out_of_normal_deliveries.html.erb
<div class="row">
  <div class="col-lg-12">
    <h3>Out of Normal Deliveries</h3>
    <%=  search_form_for(@q, url: out_of_normal_deliveries_path, class: 'form-inline') do |f| %>
      <div class="form-group">
        <%= f.label :order_number_cont %>
        <%= f.search_field :order_number_cont, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :tracking_number_cont %>
        <%= f.search_field :tracking_number_cont, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :vendor_name_cont %>
        <%= f.search_field :vendor_name_cont, class: 'form-control' %>
      </div>

      <%= f.submit class: 'btn btn-default' %>
    <% end %>

    <br>
      <%= will_paginate @orders %>
    <br>


    <table class="table table-stripped">
      <thead>
        <tr>
          <th>Order Number</th>
          <th>Vendor</th>
          <th>Tracking Number</th>
          <th>Shipped on</th>
          <th>Delivered at</th>
          <th>Shipping duration (days)</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'dashboard/out_of_normal_order', collection: @orders, as: :order %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
  <div class="col-md-12">
    <div class="alert alert-<%= alert_type(type) %>">
      <%= message %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">PackageTracker</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= current_page?(:dashboard, :index) ? 'active' : '' %>">
          <%= link_to 'Orders to Deliver', root_path %>
        </li>
        <li class="<%= current_page?(:dashboard, :out_of_normal_deliveries) ? 'active' : '' %>">
          <%= link_to 'Out of Normal Deliveries', out_of_normal_deliveries_path %>
        </li>
        <li class="<%= current_controller?(:vendors) ? 'active' : '' %>">
          <%= link_to 'Vendors', vendors_path %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PackageTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <%= render partial: 'layouts/messages' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :shipping_address %>
    <%= form.text_field :shipping_address, id: :order_shipping_address %>
  </div>

  <div class="field">
    <%= form.label :tracking_number %>
    <%= form.text_field :tracking_number, id: :order_tracking_number %>
  </div>

  <div class="field">
    <%= form.label :vendor_id %>
    <%= form.text_field :vendor_id, id: :order_vendor_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :order_status %>
  </div>

  <div class="field">
    <%= form.label :delivered_at %>
    <%= form.datetime_select :delivered_at, id: :order_delivered_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Shipping address</th>
      <th>Tracking number</th>
      <th>Vendor</th>
      <th>Status</th>
      <th>Delivered at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.shipping_address %></td>
        <td><%= order.tracking_number %></td>
        <td><%= order.vendor %></td>
        <td><%= order.status %></td>
        <td><%= order.delivered_at %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shipping address:</strong>
  <%= @order.shipping_address %>
</p>

<p>
  <strong>Tracking number:</strong>
  <%= @order.tracking_number %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @order.vendor %>
</p>

<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>

<p>
  <strong>Delivered at:</strong>
  <%= @order.delivered_at %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/vendors/_form.html.erb
<%= form_with(model: vendor, local: true) do |form| %>
  <% if vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :vendor_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<h1>Editing Vendor</h1>

<%= render 'form', vendor: @vendor %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>Vendors</h1>
    <%= link_to 'New Vendor', new_vendor_path, class: 'btn btn-primary' %>
  </div>
  <div class="col-lg-12">
    <table class='table table-stripped'>
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @vendors.each do |vendor| %>
        <tr>
          <td><%= vendor.name %></td>
          <td><%= link_to 'Show', vendor %></td>
          <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
          <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/vendors/new.html.erb
<h1>New Vendor</h1>

<%= render 'form', vendor: @vendor %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vendor.name %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>